// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdqg2LzvCs12lowOMY2gumeSbxiKrmC8A',
    appId: '1:517378528558:web:93b03bd3d141c8cda5d6bf',
    messagingSenderId: '517378528558',
    projectId: 'food-app-3eecb',
    authDomain: 'food-app-3eecb.firebaseapp.com',
    databaseURL: 'https://food-app-3eecb-default-rtdb.firebaseio.com',
    storageBucket: 'food-app-3eecb.appspot.com',
    measurementId: 'G-TF8Q2FTBZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy7GiVISsBcHFt2f_8A0Q7rJSwFAkbos8',
    appId: '1:517378528558:android:67ea602740cfdbcda5d6bf',
    messagingSenderId: '517378528558',
    projectId: 'food-app-3eecb',
    databaseURL: 'https://food-app-3eecb-default-rtdb.firebaseio.com',
    storageBucket: 'food-app-3eecb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAotDvTAa_9seK3s2Ni41hBRKTVRH5Q2IY',
    appId: '1:517378528558:ios:57a5837e71871c3fa5d6bf',
    messagingSenderId: '517378528558',
    projectId: 'food-app-3eecb',
    databaseURL: 'https://food-app-3eecb-default-rtdb.firebaseio.com',
    storageBucket: 'food-app-3eecb.appspot.com',
    androidClientId: '517378528558-5djhi5e08ske9bopa4gm4trlqhtg4091.apps.googleusercontent.com',
    iosClientId: '517378528558-dtatlk06terdogvaraufftjk1pob14ne.apps.googleusercontent.com',
    iosBundleId: 'com.example.myshoesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAotDvTAa_9seK3s2Ni41hBRKTVRH5Q2IY',
    appId: '1:517378528558:ios:57a5837e71871c3fa5d6bf',
    messagingSenderId: '517378528558',
    projectId: 'food-app-3eecb',
    databaseURL: 'https://food-app-3eecb-default-rtdb.firebaseio.com',
    storageBucket: 'food-app-3eecb.appspot.com',
    androidClientId: '517378528558-5djhi5e08ske9bopa4gm4trlqhtg4091.apps.googleusercontent.com',
    iosClientId: '517378528558-dtatlk06terdogvaraufftjk1pob14ne.apps.googleusercontent.com',
    iosBundleId: 'com.example.myshoesapp',
  );
}
